apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gx-compliance
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: gxdch-compliance
  source:
    repoURL: https://github.com/Data-Space-Core/GXDCH-Compliance.git
    targetRevision: main
    path: charts/gx-compliance
    helm:
      releaseName: main-compliance
      valueFiles:
        - ../../platform-apps/gxdch-compliance/values/gx-compliance-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gxdch-compliance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
