apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gx-notary
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: gxdch-compliance
  sources:
    - repoURL: https://gitlab.com/gaia-x/lab/compliance/gaia-x-notary-registrationnumber.git
      targetRevision: main
      path: k8s/gx-notary
      helm:
        releaseName: main-notary
        valueFiles:
          - $values/platform-apps/gxdch-compliance/values/gx-notary-values.yaml
    - repoURL: https://github.com/REPLACE_ME/GXDCH-Compliance.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: gxdch-compliance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
