apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - appproject.yaml
  - gx-registry-application.yaml
  - gx-compliance-application.yaml
  - gx-notary-application.yaml
