apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gxdch-compliance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_ME/GXDCH-Compliance.git
    targetRevision: main
    path: platform-apps/gxdch-compliance
  destination:
    server: https://kubernetes.default.svc
    namespace: gxdch-compliance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
