{{- if not .Values.existingSecret }}
apiVersion: v1
data:
  PRIVATE_KEY: {{ .Values.PRIVATE_KEY }}
  X509_CERTIFICATE: {{ .Values.X509_CERTIFICATE }}
kind: Secret
metadata:
  name: {{ include "gx-registry.fullname" . }}-keypair
{{- end }}
