apiVersion: v1
kind: Service
metadata:
  name: {{ include "gx-registry.fullname" . }}
  labels:
    {{- include "gx-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gx-registry.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gx-registry.fullname" . }}-kubo
spec:
  clusterIP: None
  ports:
    - port: 4001
      targetPort: 4001
      name: swarm
    - port: 5001
      targetPort: 5001
      name: api
    - port: 8080
      targetPort: 8080
      name: gateway
  selector:
    {{- include "gx-registry.selectorLabelsKubo" . | nindent 4 }}