{{- if not .Values.existingSecret }}
apiVersion: v1
data:
  key: {{ .Values.PRIVATE_KEY }}
  x509: {{ .Values.X509_CERTIFICATE }}
kind: Secret
metadata:
  name: {{ include "gx-compliance.fullname" . }}-secrets
{{- end }}
